# Generated by Django 2.2.14 on 2020-11-22 11:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FormCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='カテゴリー名')),
            ],
        ),
        migrations.CreateModel(
            name='FormMaterial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='カテゴリー名')),
            ],
        ),
        migrations.CreateModel(
            name='FormLabel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='フォーム名')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='axios.FormCategory')),
            ],
        ),
        migrations.AddField(
            model_name='formcategory',
            name='items',
            field=models.ManyToManyField(to='axios.FormMaterial'),
        ),
    ]
