# Generated by Django 2.2.14 on 2020-11-22 14:56

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('axios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='formmaterial',
            name='materials',
            field=jsonfield.fields.JSONField(blank=True, null=True),
        ),
    ]
