# Generated by Django 3.1.4 on 2020-12-28 07:54

import common.utilis
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('axios', '0002_formmaterial_materials'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formmaterial',
            name='materials',
            field=models.JSONField(blank=True, encoder=common.utilis.ensure_ascii_false_json_encoder, null=True),
        ),
    ]
