# Generated by Django 3.1.4 on 2020-12-28 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pdf', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FormMaterial',
            new_name='PdfMaterial',
        ),
    ]
